# Generated by Django 5.0.6 on 2024-06-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_alter_location_lat_alter_location_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.DecimalField(
                decimal_places=15, max_digits=18, null=True, verbose_name="Latitude"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="long",
            field=models.DecimalField(
                decimal_places=15, max_digits=18, null=True, verbose_name="Longitude"
            ),
        ),
    ]
