# Generated by Django 5.0.6 on 2024-06-08 13:14

import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0004_alter_location_lat_alter_location_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="geom",
            field=djgeojson.fields.PointField(null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.FloatField(default=0, verbose_name="Latitude"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="location",
            name="long",
            field=models.FloatField(default=0, verbose_name="Longitude"),
            preserve_default=False,
        ),
    ]
