# Generated by Django 5.0.6 on 2024-06-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0005_alter_location_geom_alter_location_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.FloatField(null=True, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="location",
            name="long",
            field=models.FloatField(null=True, verbose_name="Longitude"),
        ),
    ]
