# Generated by Django 5.1 on 2024-08-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_alter_location_lat_alter_location_long"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="lat",
            field=models.FloatField(default=0, verbose_name="Latitude"),
        ),
        migrations.AlterField(
            model_name="location",
            name="long",
            field=models.FloatField(default=0, verbose_name="Longitude"),
        ),
    ]
