# Generated by Django 5.1 on 2024-08-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0006_alter_location_lat_alter_location_long"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="lat",
        ),
        migrations.RemoveField(
            model_name="location",
            name="long",
        ),
    ]
